### ISSUE TITLE
Project Maintenance updates

### ISSUE THREAD

**Issue by khanzzirfan** [jedateach/pixijs-free-transform-tool#6]
Hello, 
wonder if you are still maintaing this project? The tranform tool is really helpful and definately improves use of Pixi experience. 
Pixi js is growing too fast and lot of features in Pixi right now but lacking the proper transform tool. 

Wonder if you have capacity to update this project to latest pixijs code and es7 module.  I tried intially my best, but not 100% successful. 
converstion code is here .
https://codesandbox.io/s/react-pixi-graphcs-transform-test-cf3420?file=/src/FreeTransformTool.js:756-771

**Comment by jedateach** [comment]
Hi @khanzzirfan - yeah for the project I was working on, I actually pivoted from using createjs:
https://github.com/jedateach/createjs-free-transform-tool

...to pixijs.

however, I never quite managed to get it to work in the same way.
I'm not working on this project at present - possibly never.

Pixi definitely needs a decent free transform tool to help enable graphics applications.

Thanks for trying.

**Comment by jedateach** [comment]
PS. see #5
